srun48 bash ./tools/detection/dist_train.sh configs/detection/attention_rpn/coco/attention_rpn_faster_rcnn_r50_c4_coco_base_training.py 4 --work-dir ./work_dirs/attention_rpn_faster_rcnn_r50_c4_coco_base_training_seed_11111 --seed 11111
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split1/tfa_r101_fpn_voc_split1_base_training.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154 --options "load_from='d2_voc_base_init/mm_seed_8303154.pth'"
#srun48 python3 -m tools.models.ckpt_surgery --src1 work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154/latest.pth --method randinit --save-dir work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split1/tfa_r101_fpn_voc_split1_1shot_finetuning.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_1shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split1/tfa_r101_fpn_voc_split1_2shot_finetuning.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_2shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split1/tfa_r101_fpn_voc_split1_3shot_finetuning.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_3shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split1/tfa_r101_fpn_voc_split1_5shot_finetuning.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_5shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split1/tfa_r101_fpn_voc_split1_10shot_finetuning.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_10shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split1_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split2/tfa_faster_rcnn_r101_fpn_voc_split2_base_training.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154 --options "load_from='d2_voc_base_init/mm_seed_8303154.pth'"
#srun48 python3 -m tools.models.ckpt_surgery --src1 work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154/latest.pth --method randinit --save-dir work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split2/tfa_faster_rcnn_r101_fpn_voc_split2_1shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_1shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split2/tfa_faster_rcnn_r101_fpn_voc_split2_2shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_2shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split2/tfa_faster_rcnn_r101_fpn_voc_split2_3shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_3shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split2/tfa_faster_rcnn_r101_fpn_voc_split2_5shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_5shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split2/tfa_faster_rcnn_r101_fpn_voc_split2_10shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_10shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split2_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split3/tfa_faster_rcnn_r101_fpn_voc_split3_base_training.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154 --options "load_from='d2_voc_base_init/mm_seed_8303154.pth'"
#srun48 python3 -m tools.models.ckpt_surgery --src1 work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154/latest.pth --method randinit --save-dir work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split3/tfa_faster_rcnn_r101_fpn_voc_split3_1shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_1shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split3/tfa_faster_rcnn_r101_fpn_voc_split3_2shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_2shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split3/tfa_faster_rcnn_r101_fpn_voc_split3_3shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_3shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split3/tfa_faster_rcnn_r101_fpn_voc_split3_5shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_5shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/tfa/voc/split3/tfa_faster_rcnn_r101_fpn_voc_split3_10shot_ft.py 8 --work-dir ./work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_10shot_ft_d2init_seed_8303154 --options "load_from='work_dirs/tfa_faster_rcnn_r101_fpn_voc_split3_base_training_d2init_seed_8303154/model_reset_surgery.pth'"
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_1shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_2shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_3shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_5shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_10shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_1shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_2shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_3shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_5shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_10shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_1shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_2shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_3shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_5shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_10shot-fine-tuning.py 8
#srun48 bash ./tools/detection/dist_train.sh configs/detection/fsdetview/voc/split1/fsdetview_r101_c4_8xb4_voc-split1_base-training.py 8 --work-dir ./work_dirs/fsdetview_faster_rcnn_r101_c4_voc_split1_base_training_wp500
srun49 bash ./tools/detection/dist_train.sh configs/detection/tfa/coco/tfa_faster_rcnn_r101_fpn_coco_base_training.py 8
srun49 bash ./tools/detection/dist_train.sh configs/detection/tfa/coco/tfa_faster_rcnn_r101_fpn_coco_base_training.py 8
